# vim: ts=2:sw=2:softtabstop=2

version: 2
jobs:
  build:
    docker:
      - image: jaustinpage/frc_rekt

    working_directory: ~/frc_rekt
    steps:
      - checkout

      - restore-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}

      - run:
          command: scripts/dependencies

      - run:
          command: scripts/test

      - save-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}
          paths:
            - ./data/vex

      - store_artifacts:
          path: artifacts/
          destination: test
