# vim: ts=2:sw=2:softtabstop=2

version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    working_directory: ~/frc_rekt
    steps:
      - checkout

      - restore-cache:
          key: v2-requirements.txt-{{ checksum "requirements.txt" }}

      - restore-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}

      - run:
          command: |
            apt-get update
            apt-get install -y ca-certificates
            scripts/dependencies

      - run:
          command: scripts/test

      - save-cache:
          key: v2-requirements.txt-{{ checksum "requirements.txt" }}
          paths:
            - ./env

      - save-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}
          paths:
            - ./data/vex

      - store_artifacts:
          path: artifacts/
          destination: test
