# vim: ts=2:sw=2:softtabstop=2

version: 2
jobs:
  build:
    docker:
      - image: jaustinpage/frc_rekt

    working_directory: /app/
    steps:
      - checkout

      - restore-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}

      - run:
          command: |
            scripts/py-dependencies
            scripts/download_curves
            scripts/test

      - save-cache:
          key: v2-download_curves.py-{{ checksum "data/vex/download_curves.py" }}
          paths:
            - ./data/vex

      - store_artifacts:
          path: artifacts/
          destination: test

  build_container:
    docker:
      - image: alpine

    working_directory: /root/
    steps:
      - checkout

      - setup-remote-docker

      - run:
          name: Install Docker client
          command: |
            set -x
            curl -fsSLO https://get.docker.com/builds/Linux/x86_64/docker-17.04.0-ce.tgz && tar --strip-components=1 -xvzf docker-17.04.0-ce.tgz -C /usr/local/bin #https://get.docker.com/builds/

      - run:
          command: |
            TAG=$CIRCLE_SHA1
            docker build -t jaustinpage/frc_rekt:latest -t jaustinpage/frc_rekt:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push jaustinpage/frc_rekt:latest
